<a href="https://colab.research.google.com/github/mpradeep2005/Pytorch/blob/main/Random_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

#Random tensors

In [ ]:
random=torch.rand(3,5)
random

tensor([[0.7688, 0.2459, 0.1880, 0.0152, 0.3240],
        [0.3914, 0.4557, 0.5358, 0.4878, 0.4554],
        [0.7553, 0.7010, 0.9916, 0.6326, 0.1996]])

In [ ]:
tensor=torch.rand(2,2,3,4,5)
tensor

## using size

In [ ]:
size=torch.rand(size=(255,255,3))
size

## Creating Zeros

In [ ]:
zero=torch.zeros(3,5)
zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Creating Ones

In [ ]:
ones=torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Dtypes and ndim


In [ ]:
print(ones.dtype)
print(ones.shape)
print(ones.ndim)

torch.float32
torch.Size([3, 5])
2
