<a href="https://colab.research.google.com/github/mpradeep2005/Pytorch/blob/main/Range.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

#Creating Range

In [3]:
# Range will be not available in future so use arange
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

###we can use arange like pythons range

In [8]:
one_to_ten=torch.arange(0,10,2)
one_to_ten

tensor([0, 2, 4, 6, 8])

#Creating tensors like

this will create a range like (Start,End,Skip)

In [9]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [10]:
ten_ones=torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1])