<a href="https://colab.research.google.com/github/mpradeep2005/Pytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [6]:
torch.__version__

'2.8.0+cu126'

In [15]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [10]:
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [16]:
matrix=torch.tensor([[1,2,3],
                     [4,5,6]])
print(matrix)
print(matrix.shape)
matrix.ndim

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


2

In [22]:
Tensor=torch.tensor([ [1,2,3],
                      [1,3,4],
                      [3,7,3],
                      [8,5,6],
                      [8,2,56]])
print(Tensor)
print(Tensor.shape)
print(Tensor.ndim)

tensor([[ 1,  2,  3],
        [ 1,  3,  4],
        [ 3,  7,  3],
        [ 8,  5,  6],
        [ 8,  2, 56]])
torch.Size([5, 3])
2
